/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSkillsIndexRouteImport } from './routes/docs/skills/index'
import { Route as DocsSkillsCategoryIndexRouteImport } from './routes/docs/skills/$category/index'
import { Route as DocsSkillsCategoryNameRouteImport } from './routes/docs/skills/$category/$name'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSkillsIndexRoute = DocsSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSkillsCategoryIndexRoute = DocsSkillsCategoryIndexRouteImport.update({
  id: '/skills/$category/',
  path: '/skills/$category/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSkillsCategoryNameRoute = DocsSkillsCategoryNameRouteImport.update({
  id: '/skills/$category/$name',
  path: '/skills/$category/$name',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/skills/': typeof DocsSkillsIndexRoute
  '/docs/skills/$category/$name': typeof DocsSkillsCategoryNameRoute
  '/docs/skills/$category/': typeof DocsSkillsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/skills': typeof DocsSkillsIndexRoute
  '/docs/skills/$category/$name': typeof DocsSkillsCategoryNameRoute
  '/docs/skills/$category': typeof DocsSkillsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/skills/': typeof DocsSkillsIndexRoute
  '/docs/skills/$category/$name': typeof DocsSkillsCategoryNameRoute
  '/docs/skills/$category/': typeof DocsSkillsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/skills/'
    | '/docs/skills/$category/$name'
    | '/docs/skills/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/skills'
    | '/docs/skills/$category/$name'
    | '/docs/skills/$category'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/skills/'
    | '/docs/skills/$category/$name'
    | '/docs/skills/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/skills/': {
      id: '/docs/skills/'
      path: '/skills'
      fullPath: '/docs/skills/'
      preLoaderRoute: typeof DocsSkillsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/skills/$category/': {
      id: '/docs/skills/$category/'
      path: '/skills/$category'
      fullPath: '/docs/skills/$category/'
      preLoaderRoute: typeof DocsSkillsCategoryIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/skills/$category/$name': {
      id: '/docs/skills/$category/$name'
      path: '/skills/$category/$name'
      fullPath: '/docs/skills/$category/$name'
      preLoaderRoute: typeof DocsSkillsCategoryNameRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsSkillsIndexRoute: typeof DocsSkillsIndexRoute
  DocsSkillsCategoryNameRoute: typeof DocsSkillsCategoryNameRoute
  DocsSkillsCategoryIndexRoute: typeof DocsSkillsCategoryIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsSkillsIndexRoute: DocsSkillsIndexRoute,
  DocsSkillsCategoryNameRoute: DocsSkillsCategoryNameRoute,
  DocsSkillsCategoryIndexRoute: DocsSkillsCategoryIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
