/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as DocsSkillsRouteImport } from './routes/docs/skills'
import { Route as SkillsCategoryNameRouteImport } from './routes/skills/$category.$name'
import { Route as DocsSkillsCategoryNameRouteImport } from './routes/docs/skills/$category.$name'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SkillsRoute,
} as any)
const DocsSkillsRoute = DocsSkillsRouteImport.update({
  id: '/docs/skills',
  path: '/docs/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsCategoryNameRoute = SkillsCategoryNameRouteImport.update({
  id: '/$category/$name',
  path: '/$category/$name',
  getParentRoute: () => SkillsRoute,
} as any)
const DocsSkillsCategoryNameRoute = DocsSkillsCategoryNameRouteImport.update({
  id: '/$category/$name',
  path: '/$category/$name',
  getParentRoute: () => DocsSkillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRouteWithChildren
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/skills/': typeof SkillsIndexRoute
  '/skills/$category/$name': typeof SkillsCategoryNameRoute
  '/docs/skills/$category/$name': typeof DocsSkillsCategoryNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/skills': typeof SkillsIndexRoute
  '/skills/$category/$name': typeof SkillsCategoryNameRoute
  '/docs/skills/$category/$name': typeof DocsSkillsCategoryNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills': typeof SkillsRouteWithChildren
  '/docs/skills': typeof DocsSkillsRouteWithChildren
  '/skills/': typeof SkillsIndexRoute
  '/skills/$category/$name': typeof SkillsCategoryNameRoute
  '/docs/skills/$category/$name': typeof DocsSkillsCategoryNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skills'
    | '/docs/skills'
    | '/skills/'
    | '/skills/$category/$name'
    | '/docs/skills/$category/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/skills'
    | '/skills'
    | '/skills/$category/$name'
    | '/docs/skills/$category/$name'
  id:
    | '__root__'
    | '/'
    | '/skills'
    | '/docs/skills'
    | '/skills/'
    | '/skills/$category/$name'
    | '/docs/skills/$category/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  DocsSkillsRoute: typeof DocsSkillsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/docs/skills': {
      id: '/docs/skills'
      path: '/docs/skills'
      fullPath: '/docs/skills'
      preLoaderRoute: typeof DocsSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$category/$name': {
      id: '/skills/$category/$name'
      path: '/$category/$name'
      fullPath: '/skills/$category/$name'
      preLoaderRoute: typeof SkillsCategoryNameRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/docs/skills/$category/$name': {
      id: '/docs/skills/$category/$name'
      path: '/$category/$name'
      fullPath: '/docs/skills/$category/$name'
      preLoaderRoute: typeof DocsSkillsCategoryNameRouteImport
      parentRoute: typeof DocsSkillsRoute
    }
  }
}

interface SkillsRouteChildren {
  SkillsIndexRoute: typeof SkillsIndexRoute
  SkillsCategoryNameRoute: typeof SkillsCategoryNameRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsIndexRoute: SkillsIndexRoute,
  SkillsCategoryNameRoute: SkillsCategoryNameRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

interface DocsSkillsRouteChildren {
  DocsSkillsCategoryNameRoute: typeof DocsSkillsCategoryNameRoute
}

const DocsSkillsRouteChildren: DocsSkillsRouteChildren = {
  DocsSkillsCategoryNameRoute: DocsSkillsCategoryNameRoute,
}

const DocsSkillsRouteWithChildren = DocsSkillsRoute._addFileChildren(
  DocsSkillsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsRoute: SkillsRouteWithChildren,
  DocsSkillsRoute: DocsSkillsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
